//! `agentoven login` — authenticate with the control plane.

use clap::Args;
use colored::Colorize;

#[derive(Args)]
pub struct LoginArgs {
    /// API key (or use interactive prompt).
    #[arg(long)]
    pub api_key: Option<String>,

    /// Control plane URL.
    #[arg(long)]
    pub url: Option<String>,
}

pub async fn execute(args: LoginArgs) -> anyhow::Result<()> {
    println!("\n  {} Authenticating with AgentOven...\n", "🔑".to_string());

    let api_key = if let Some(key) = args.api_key {
        key
    } else {
        // Interactive prompt
        dialoguer::Password::new()
            .with_prompt("  Enter your API key")
            .interact()?
    };

    let url = args
        .url
        .unwrap_or_else(|| "http://localhost:8080".into());

    // Store in config file
    let config_dir = dirs::home_dir()
        .map(|h| h.join(".agentoven"))
        .expect("Cannot determine home directory");

    tokio::fs::create_dir_all(&config_dir).await?;

    let config = format!(
        r#"# AgentOven CLI configuration
# Generated by `agentoven login`

url = "{url}"
api_key = "{api_key}"
"#
    );

    let config_path = config_dir.join("config.toml");
    tokio::fs::write(&config_path, config).await?;

    println!(
        "  {} Authenticated! Config saved to {}",
        "✓".green().bold(),
        config_path.display().to_string().cyan()
    );
    println!(
        "  {} Connected to: {}",
        "→".dimmed(),
        url.cyan()
    );
    Ok(())
}
