-- Rollback initial schema

DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS traces CASCADE;
DROP TABLE IF EXISTS model_providers CASCADE;
DROP TABLE IF EXISTS recipe_runs CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS agent_versions CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS kitchens CASCADE;
